import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000';

function App(){
  const [step,setStep]=useState('setup');
  const [jd,setJd]=useState(''); const [file,setFile]=useState(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  const [assessment,setAssessment]=useState(null); const [interview,setInterview]=useState(null); const [answer,setAnswer]=useState(''); const [report,setReport]=useState(null);
  const submit=async()=>{
    if(!jd || !file){setError('Add a job description and resume first.');return}
    setLoading(true);setError('');
    try{const fd=new FormData();fd.append('job_description',jd);fd.append('resume',file);const r=await fetch(`${API}/api/assessments`,{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw Error(d.detail||'Analysis failed');setAssessment(d);setStep('analysis')}
    catch(e){setError(e.message)}finally{setLoading(false)}
  };
  const start=async()=>{setLoading(true);setError('');try{const r=await fetch(`${API}/api/interviews`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assessment_id:assessment.id})});const d=await r.json();if(!r.ok)throw Error(d.detail);setInterview(d);setStep('interview')}catch(e){setError(e.message)}finally{setLoading(false)}};
  const sendAnswer=async()=>{if(!answer.trim())return;setLoading(true);setError('');try{const r=await fetch(`${API}/api/interviews/${interview.id}/answer`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answer})});const d=await r.json();if(!r.ok)throw Error(d.detail);setAnswer('');if(d.completed){setReport(d.report);setStep('report')}else setInterview({...interview,...d.next_question,question_number:d.question_number})}catch(e){setError(e.message)}finally{setLoading(false)}};
  return <div className="app"><header><div className="brand"><span className="mark">E</span><span>EvidenceHire</span></div><span className="tag">Understand what candidates actually built.</span></header>
  <main>
    {error&&<div className="error">{error}</div>}
    {step==='setup'&&<section className="hero"><div className="eyebrow">TECHNICAL HIRING • MVP</div><h1>Don't hire the <em>resume.</em><br/>Hire the evidence.</h1><p className="lead">Turn resume claims into evidence gaps, run a short adaptive interview, and see what the candidate actually demonstrated.</p><div className="grid"><div className="panel"><label>Job description</label><textarea value={jd} onChange={e=>setJd(e.target.value)} placeholder="Paste the role requirements…"/><div className="upload"><input id="resume" type="file" accept=".pdf,.docx,.txt" onChange={e=>setFile(e.target.files[0])}/><label htmlFor="resume">{file?`✓ ${file.name}`:'Upload candidate resume (PDF, DOCX, TXT)'}</label></div><button onClick={submit} disabled={loading}>{loading?'Analyzing evidence…':'Analyze candidate →'}</button></div><div className="side"><div className="mini"><b>01</b><div><strong>Extract claims</strong><span>Separate keywords from concrete experience.</span></div></div><div className="mini"><b>02</b><div><strong>Find evidence gaps</strong><span>Identify what still needs verification.</span></div></div><div className="mini"><b>03</b><div><strong>Test depth</strong><span>Ask adaptive questions based on the role.</span></div></div></div></div></section>}
    {step==='analysis'&&<Analysis data={assessment} onStart={start} loading={loading}/>} 
    {step==='interview'&&<Interview data={interview} answer={answer} setAnswer={setAnswer} onSend={sendAnswer} loading={loading}/>} 
    {step==='report'&&<Report report={report}/>} 
  </main></div>
}
function Analysis({data,onStart,loading}){const a=data.analysis;return <section className="section"><div className="topline"><div><div className="eyebrow">CANDIDATE ANALYSIS</div><h2>{a.candidate_name}</h2><p>{a.role_title}</p></div><button onClick={onStart} disabled={loading}>{loading?'Preparing…':'Start adaptive interview →'}</button></div><div className="cards"><div className="card"><span className="muted">ROLE REQUIREMENTS</span>{a.requirements.map((x,i)=><div className="req" key={i}><div><strong>{x.skill}</strong><span>{x.importance}</span></div><ul>{x.evidence_to_verify.map((e,j)=><li key={j}>{e}</li>)}</ul></div>)}</div><div className="card"><span className="muted">RESUME CLAIMS</span>{a.claims.map((x,i)=><div className="claim" key={i}><div className="claimhead"><strong>{x.skill}</strong><span>{Math.round(x.confidence*100)}% confidence</span></div><p>{x.claim}</p><small>{x.evidence_in_resume}</small></div>)}<span className="muted gaptitle">EVIDENCE GAPS</span>{a.evidence_gaps.map((x,i)=><div className="gap" key={i}>⚠ {x}</div>)}</div></div></section>}
function Interview({data,answer,setAnswer,onSend,loading}){return <section className="interview"><div className="eyebrow">ADAPTIVE INTERVIEW • QUESTION {data.question_number}</div><div className="question"><span>{data.skill}</span><h2>{data.question}</h2><p>Answer with a real project example. Explain what you personally owned, the technical decisions you made, and the outcome.</p></div><textarea autoFocus value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Describe the project, your role, decisions, tradeoffs, and results…"/><div className="interfoot"><span>{answer.length} characters</span><button onClick={onSend} disabled={loading||!answer.trim()}>{loading?'Evaluating…':'Submit answer →'}</button></div></section>}
function Report({report}){return <section className="section"><div className="reporthero"><div><div className="eyebrow">EVIDENCE REPORT</div><h2>What this candidate actually demonstrated</h2></div><div className="score"><strong>{report.overall_score.toFixed(1)}</strong><span>/ 10</span><small>{report.recommendation}</small></div></div><div className="cards"><div className="card"><span className="muted">STRENGTHS</span>{report.strengths.map((x,i)=><div className="positive" key={i}>✓ {x}</div>)}<span className="muted gaptitle">RISKS / UNCERTAINTY</span>{report.risks.map((x,i)=><div className="gap" key={i}>⚠ {x}</div>)}</div><div className="card"><span className="muted">SKILL EVIDENCE</span>{report.skills.map((x,i)=><div className="skill" key={i}><div className="skilltop"><strong>{x.skill}</strong><b>{x.score.toFixed(1)}</b></div><div className="bar"><i style={{width:`${x.score*10}%`}}/></div><p><b>Claim:</b> {x.claim}</p><p><b>Demonstrated:</b> {x.demonstrated_evidence}</p><p className="uncertain"><b>Uncertainty:</b> {x.uncertainty}</p></div>)}</div></div><div className="summary"><span className="muted">HIRING SUMMARY</span><p>{report.hiring_summary}</p><span className="confidence">Evidence confidence: {Math.round(report.evidence_confidence*100)}%</span></div></section>}

createRoot(document.getElementById('root')).render(<App/>);
